/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PetIdRouteImport } from './routes/pet.$id'
import { Route as PetsNovoRouteImport } from './routes/pets.novo'
import { Route as PetsIdEditarRouteImport } from './routes/pets.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PetIdRoute = PetIdRouteImport.update({
  id: '/pet/$id',
  path: '/pet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNovoRoute = PetsNovoRouteImport.update({
  id: '/pets/novo',
  path: '/pets/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIdEditarRoute = PetsIdEditarRouteImport.update({
  id: '/pets/$id/editar',
  path: '/pets/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/pet/$id': typeof PetIdRoute
  '/pets/novo': typeof PetsNovoRoute
  '/pets/$id/editar': typeof PetsIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/pet/$id': typeof PetIdRoute
  '/pets/novo': typeof PetsNovoRoute
  '/pets/$id/editar': typeof PetsIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/pet/$id': typeof PetIdRoute
  '/pets/novo': typeof PetsNovoRoute
  '/pets/$id/editar': typeof PetsIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/perfil'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/pet/$id'
    | '/pets/novo'
    | '/pets/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/perfil'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/pet/$id'
    | '/pets/novo'
    | '/pets/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/perfil'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/pet/$id'
    | '/pets/novo'
    | '/pets/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  PetIdRoute: typeof PetIdRoute
  PetsNovoRoute: typeof PetsNovoRoute
  PetsIdEditarRoute: typeof PetsIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet/$id': {
      id: '/pet/$id'
      path: '/pet/$id'
      fullPath: '/pet/$id'
      preLoaderRoute: typeof PetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/novo': {
      id: '/pets/novo'
      path: '/pets/novo'
      fullPath: '/pets/novo'
      preLoaderRoute: typeof PetsNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$id/editar': {
      id: '/pets/$id/editar'
      path: '/pets/$id/editar'
      fullPath: '/pets/$id/editar'
      preLoaderRoute: typeof PetsIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  PetIdRoute: PetIdRoute,
  PetsNovoRoute: PetsNovoRoute,
  PetsIdEditarRoute: PetsIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
